services:
  minecraft-server:
    image: thewrongjames/minecraft-server:latest
    container_name: minecraft-server_server
    volumes:
      - type: volume
        source: persistent-files
        target: /opt/minecraft/server-files
        cpu_count: 3.5
        restart: unless-stopped
    environment:
      RAM: 3G
    ports:
      - 25565:25565
    # So that `docker container attach ...` works.
    stdin_open: true
    tty: true


volumes:
  persistent-files:
    name: minecraft-server_persistent-files