services:
  minecraft-server:
    image: thewrongjames/minecraft-server:latest
    container_name: minecraft-server_server
    volumes:
      - type: volume
        source: persistent-files
        target: /opt/minecraft/server-files
    environment:
      RAM: 2G
    deploy:
      resources:
        limits:
          cpus: '3'
    restart: unless-stopped
    ports:
      - 25565:25565
    # So that `docker container attach ...` works.
    stdin_open: true
    tty: true


volumes:
  persistent-files:
    name: minecraft-server_persistent-files